//! Compatibility tests with C minisign
//!
//! These tests verify that the Rust implementation can correctly parse
//! and verify signatures generated by the C implementation.

use minisign::{
    crypto::{blake2b_512, verify},
    keys::PubkeyStruct,
    ops::{
        generate::{GenerateOptions, generate},
        sign::{SignOptions, sign},
    },
    signature::SignatureBox,
};
use std::{fs, process::Command};

/// Test parsing a C-generated public key file
#[test]
fn test_parse_c_generated_public_key() {
    let contents = fs::read_to_string("tests/fixtures/keys/unencrypted.pub")
        .expect("should read public key file");

    let pubkey = PubkeyStruct::from_file_contents(&contents).expect("should parse public key");

    // Verify we can access the parsed data
    assert_eq!(pubkey.keynum().as_bytes().len(), 8);
    assert_eq!(pubkey.public_key().as_bytes().len(), 32);
}

/// Test parsing a C-generated signature file
#[test]
fn test_parse_c_generated_signature() {
    let contents = fs::read_to_string("tests/fixtures/signatures/hello.txt.minisig")
        .expect("should read signature file");

    let sig_box = SignatureBox::from_file_contents(&contents).expect("should parse signature");

    // Verify the structure
    assert_eq!(sig_box.untrusted_comment(), "Test signature");
    assert_eq!(sig_box.trusted_comment(), "Signed with Rust test key");
    // C minisign uses prehashed mode by default for files
    assert!(sig_box.sig_struct().is_prehashed());
}

/// Test verifying a C-generated signature
#[test]
fn test_verify_c_generated_signature() {
    // Load the public key
    let pubkey_contents = fs::read_to_string("tests/fixtures/keys/unencrypted.pub")
        .expect("should read public key file");
    let pubkey =
        PubkeyStruct::from_file_contents(&pubkey_contents).expect("should parse public key");

    // Load the signature
    let sig_contents = fs::read_to_string("tests/fixtures/signatures/hello.txt.minisig")
        .expect("should read signature file");
    let sig_box = SignatureBox::from_file_contents(&sig_contents).expect("should parse signature");

    // Load the message
    let message = fs::read("tests/fixtures/messages/hello.txt").expect("should read message");

    // For prehashed signatures, we need to hash the message first
    let data_to_verify = if sig_box.sig_struct().is_prehashed() {
        blake2b_512(&message).to_vec()
    } else {
        message.clone()
    };

    // Verify the signature on the message (or its hash for prehashed mode)
    verify(
        pubkey.public_key(),
        &data_to_verify,
        sig_box.sig_struct().signature(),
    )
    .expect("signature should verify");

    // Verify the global signature (trusted comment binding)
    sig_box
        .verify_global_signature(pubkey.public_key())
        .expect("global signature should verify");
}

/// Test that signature verification fails with wrong message
#[test]
fn test_verify_c_generated_signature_wrong_message() {
    let pubkey_contents = fs::read_to_string("tests/fixtures/keys/unencrypted.pub")
        .expect("should read public key file");
    let pubkey =
        PubkeyStruct::from_file_contents(&pubkey_contents).expect("should parse public key");

    let sig_contents = fs::read_to_string("tests/fixtures/signatures/hello.txt.minisig")
        .expect("should read signature file");
    let sig_box = SignatureBox::from_file_contents(&sig_contents).expect("should parse signature");

    // Try to verify with wrong message
    let wrong_message = b"Wrong message";

    // Handle prehashed mode
    let data_to_verify = if sig_box.sig_struct().is_prehashed() {
        blake2b_512(wrong_message).to_vec()
    } else {
        wrong_message.to_vec()
    };

    let result = verify(
        pubkey.public_key(),
        &data_to_verify,
        sig_box.sig_struct().signature(),
    );

    assert!(result.is_err(), "should fail with wrong message");
}

/// Test that signature verification fails with wrong public key
#[test]
fn test_verify_c_generated_signature_wrong_key() {
    // Use the other public key
    let pubkey_contents =
        fs::read_to_string("tests/fixtures/keys/test.pub").expect("should read public key file");
    let pubkey =
        PubkeyStruct::from_file_contents(&pubkey_contents).expect("should parse public key");

    let sig_contents = fs::read_to_string("tests/fixtures/signatures/hello.txt.minisig")
        .expect("should read signature file");
    let sig_box = SignatureBox::from_file_contents(&sig_contents).expect("should parse signature");

    let message = fs::read("tests/fixtures/messages/hello.txt").expect("should read message");

    // Handle prehashed mode
    let data_to_verify = if sig_box.sig_struct().is_prehashed() {
        blake2b_512(&message).to_vec()
    } else {
        message.clone()
    };

    // Try to verify with wrong public key
    let result = verify(
        pubkey.public_key(),
        &data_to_verify,
        sig_box.sig_struct().signature(),
    );

    assert!(result.is_err(), "should fail with wrong key");
}

/// Test cross-compatibility: C minisign legacy signature -> Rust verify
#[test]
fn test_verify_c_legacy_signature() {
    let temp_dir = tempfile::TempDir::new().expect("Failed to create temp dir");
    let message_file = temp_dir.path().join("legacy_test.txt");
    let sig_file = temp_dir.path().join("legacy_test.txt.minisig");
    let secret_key = temp_dir.path().join("legacy.key");
    let public_key = temp_dir.path().join("legacy.pub");

    // Create test message
    fs::write(&message_file, b"Legacy mode test message").expect("Failed to write message");

    // Generate key with C minisign
    let output = Command::new("minisign")
        .arg("-G")
        .arg("-f")
        .arg("-W")
        .arg("-s")
        .arg(&secret_key)
        .arg("-p")
        .arg(&public_key)
        .output();

    if output.is_err() || !output.as_ref().unwrap().status.success() {
        eprintln!("Warning: C minisign not available, skipping test");
        return;
    }

    // Sign with legacy mode using C minisign
    let status = Command::new("minisign")
        .arg("-S")
        .arg("-l") // Legacy mode
        .arg("-s")
        .arg(&secret_key)
        .arg("-m")
        .arg(&message_file)
        .output();

    if status.is_err() || !status.as_ref().unwrap().status.success() {
        eprintln!("Warning: C minisign sign failed, skipping test");
        return;
    }

    // Load the C-generated signature
    let sig_contents = fs::read_to_string(&sig_file).expect("Failed to read C-generated signature");
    let sig_box = SignatureBox::from_file_contents(&sig_contents)
        .expect("Failed to parse C-generated signature");

    // Verify it's NOT prehashed (legacy mode)
    assert!(
        !sig_box.sig_struct().is_prehashed(),
        "C legacy signature should not be prehashed"
    );

    // Load public key
    let pubkey_contents = fs::read_to_string(&public_key).expect("Failed to read public key");
    let pubkey =
        PubkeyStruct::from_file_contents(&pubkey_contents).expect("Failed to parse public key");

    // Load message
    let message = fs::read(&message_file).expect("Failed to read message");

    // Verify with Rust implementation (should NOT hash for legacy mode)
    let data_to_verify = if sig_box.sig_struct().is_prehashed() {
        blake2b_512(&message).to_vec()
    } else {
        message.clone()
    };

    verify(
        pubkey.public_key(),
        &data_to_verify,
        sig_box.sig_struct().signature(),
    )
    .expect("Rust should verify C legacy signature");

    // Verify global signature
    sig_box
        .verify_global_signature(pubkey.public_key())
        .expect("Global signature should verify");
}

/// Test cross-compatibility: Rust legacy signature -> C minisign verify
#[test]
fn test_c_verify_rust_legacy_signature() {
    let temp_dir = tempfile::TempDir::new().expect("Failed to create temp dir");
    let message_file = temp_dir.path().join("rust_legacy.txt");
    let sig_file = temp_dir.path().join("rust_legacy.txt.minisig");
    let secret_key = temp_dir.path().join("rust_legacy.key");
    let public_key = temp_dir.path().join("rust_legacy.pub");

    // Create test message
    fs::write(&message_file, b"Rust legacy mode test").expect("Failed to write message");

    // Generate key with Rust
    let gen_opts = GenerateOptions::new(
        secret_key.as_path(),
        public_key.as_path(),
        None,
        true,  // force
        true,  // no_password
        false, // allow_kdf_fallback
        false, // force_weak_kdf
    );
    generate(&gen_opts, None).expect("Failed to generate key");

    // Sign with Rust in legacy mode (non-prehashed)
    let sign_opts = SignOptions {
        secret_key_file: secret_key.as_path(),
        message_file: message_file.as_path(),
        signature_file: Some(sig_file.as_path()),
        prehashed: false, // Legacy mode = non-prehashed
        trusted_comment: None,
        untrusted_comment: None,
        force: true,
        quiet: false,
    };
    sign(&sign_opts, None).expect("Failed to sign");

    // Verify with C minisign
    let status = Command::new("minisign")
        .arg("-V")
        .arg("-p")
        .arg(&public_key)
        .arg("-m")
        .arg(&message_file)
        .output();

    if let Ok(output) = status {
        if output.status.success() {
            // Success!
        } else {
            panic!(
                "C minisign failed to verify Rust legacy signature: {}",
                String::from_utf8_lossy(&output.stderr)
            );
        }
    } else {
        eprintln!("Warning: C minisign not available, skipping verification");
    }
}
