//! Compatibility tests with C minisign
//!
//! These tests verify that the Rust implementation can correctly parse
//! and verify signatures generated by the C implementation.

use minisign::{
    crypto::{blake2b_512, verify},
    keys::PubkeyStruct,
    signature::SignatureBox,
};
use std::fs;

/// Test parsing a C-generated public key file
#[test]
fn test_parse_c_generated_public_key() {
    let contents = fs::read_to_string("tests/fixtures/keys/unencrypted.pub")
        .expect("should read public key file");

    let pubkey = PubkeyStruct::from_file_contents(&contents).expect("should parse public key");

    // Verify we can access the parsed data
    assert_eq!(pubkey.keynum().as_bytes().len(), 8);
    assert_eq!(pubkey.public_key().as_bytes().len(), 32);
}

/// Test parsing a C-generated signature file
#[test]
fn test_parse_c_generated_signature() {
    let contents = fs::read_to_string("tests/fixtures/signatures/hello.txt.minisig")
        .expect("should read signature file");

    let sig_box = SignatureBox::from_file_contents(&contents).expect("should parse signature");

    // Verify the structure
    assert_eq!(sig_box.untrusted_comment(), "Test signature");
    assert_eq!(sig_box.trusted_comment(), "Signed with Rust test key");
    // C minisign uses prehashed mode by default for files
    assert!(sig_box.sig_struct().is_prehashed());
}

/// Test verifying a C-generated signature
#[test]
fn test_verify_c_generated_signature() {
    // Load the public key
    let pubkey_contents = fs::read_to_string("tests/fixtures/keys/unencrypted.pub")
        .expect("should read public key file");
    let pubkey =
        PubkeyStruct::from_file_contents(&pubkey_contents).expect("should parse public key");

    // Load the signature
    let sig_contents = fs::read_to_string("tests/fixtures/signatures/hello.txt.minisig")
        .expect("should read signature file");
    let sig_box = SignatureBox::from_file_contents(&sig_contents).expect("should parse signature");

    // Load the message
    let message = fs::read("tests/fixtures/messages/hello.txt").expect("should read message");

    // For prehashed signatures, we need to hash the message first
    let data_to_verify = if sig_box.sig_struct().is_prehashed() {
        blake2b_512(&message).to_vec()
    } else {
        message.clone()
    };

    // Verify the signature on the message (or its hash for prehashed mode)
    verify(
        pubkey.public_key(),
        &data_to_verify,
        sig_box.sig_struct().signature(),
    )
    .expect("signature should verify");

    // Verify the global signature (trusted comment binding)
    sig_box
        .verify_global_signature(pubkey.public_key())
        .expect("global signature should verify");
}

/// Test that signature verification fails with wrong message
#[test]
fn test_verify_c_generated_signature_wrong_message() {
    let pubkey_contents = fs::read_to_string("tests/fixtures/keys/unencrypted.pub")
        .expect("should read public key file");
    let pubkey =
        PubkeyStruct::from_file_contents(&pubkey_contents).expect("should parse public key");

    let sig_contents = fs::read_to_string("tests/fixtures/signatures/hello.txt.minisig")
        .expect("should read signature file");
    let sig_box = SignatureBox::from_file_contents(&sig_contents).expect("should parse signature");

    // Try to verify with wrong message
    let wrong_message = b"Wrong message";

    // Handle prehashed mode
    let data_to_verify = if sig_box.sig_struct().is_prehashed() {
        blake2b_512(wrong_message).to_vec()
    } else {
        wrong_message.to_vec()
    };

    let result = verify(
        pubkey.public_key(),
        &data_to_verify,
        sig_box.sig_struct().signature(),
    );

    assert!(result.is_err(), "should fail with wrong message");
}

/// Test that signature verification fails with wrong public key
#[test]
fn test_verify_c_generated_signature_wrong_key() {
    // Use the other public key
    let pubkey_contents =
        fs::read_to_string("tests/fixtures/keys/test.pub").expect("should read public key file");
    let pubkey =
        PubkeyStruct::from_file_contents(&pubkey_contents).expect("should parse public key");

    let sig_contents = fs::read_to_string("tests/fixtures/signatures/hello.txt.minisig")
        .expect("should read signature file");
    let sig_box = SignatureBox::from_file_contents(&sig_contents).expect("should parse signature");

    let message = fs::read("tests/fixtures/messages/hello.txt").expect("should read message");

    // Handle prehashed mode
    let data_to_verify = if sig_box.sig_struct().is_prehashed() {
        blake2b_512(&message).to_vec()
    } else {
        message.clone()
    };

    // Try to verify with wrong public key
    let result = verify(
        pubkey.public_key(),
        &data_to_verify,
        sig_box.sig_struct().signature(),
    );

    assert!(result.is_err(), "should fail with wrong key");
}
