//! PGP Word List encoding for human-readable key fingerprints
//!
//! The PGP Word List is a phonetically distinct word list designed for conveying
//! data bytes via voice channels. Each byte value (0x00-0xFF) maps to two different
//! words depending on whether it appears at an even or odd position in the byte sequence.
//!
//! This positional encoding helps detect transposition errors when bytes are swapped.
//!
//! ## References
//!
//! - <https://en.wikipedia.org/wiki/PGP_word_list>
//! - <https://philzimmermann.com/docs/PGP_word_list.pdf>

use crate::crypto::KeyNum;

/// PGP Word List for even byte positions (two-syllable words)
///
/// Maps byte values 0x00-0xFF to phonetically distinct two-syllable words.
pub const EVEN_WORDS: [&str; 256] = [
    "aardvark",
    "absurd",
    "accrue",
    "acme",
    "adrift",
    "adult",
    "afflict",
    "ahead",
    "aimless",
    "algol",
    "allow",
    "alone",
    "ammo",
    "ancient",
    "apple",
    "artist",
    "assume",
    "athens",
    "atlas",
    "aztec",
    "baboon",
    "backfield",
    "backward",
    "basalt",
    "beaming",
    "bedlamp",
    "beehive",
    "beeswax",
    "befriend",
    "belfast",
    "berserk",
    "billiard",
    "bison",
    "blackjack",
    "blockade",
    "blowtorch",
    "bluebird",
    "bombast",
    "bookshelf",
    "brackish",
    "breadline",
    "breakup",
    "brickyard",
    "briefcase",
    "burbank",
    "button",
    "buzzard",
    "cement",
    "chairlift",
    "chatter",
    "checkup",
    "chisel",
    "choking",
    "chopper",
    "christmas",
    "clamshell",
    "classic",
    "classroom",
    "cleanup",
    "clockwork",
    "cobra",
    "commence",
    "concert",
    "cowbell",
    "crackdown",
    "cranky",
    "crowfoot",
    "crucial",
    "crumpled",
    "crusade",
    "cubic",
    "deadbolt",
    "deckhand",
    "dogsled",
    "dosage",
    "dragnet",
    "drainage",
    "dreadful",
    "drifter",
    "dropper",
    "drumbeat",
    "drunken",
    "dupont",
    "dwelling",
    "eating",
    "edict",
    "egghead",
    "eightball",
    "endorse",
    "endow",
    "enlist",
    "erase",
    "escape",
    "exceed",
    "eyeglass",
    "eyetooth",
    "facial",
    "fallout",
    "flagpole",
    "flatfoot",
    "flytrap",
    "fracture",
    "fragile",
    "framework",
    "freedom",
    "frighten",
    "gazelle",
    "geiger",
    "glasgow",
    "glitter",
    "glucose",
    "goggles",
    "goldfish",
    "gremlin",
    "guidance",
    "hamlet",
    "highchair",
    "hockey",
    "hotdog",
    "indoors",
    "indulge",
    "inverse",
    "involve",
    "island",
    "janus",
    "jawbone",
    "keyboard",
    "kickoff",
    "kiwi",
    "klaxon",
    "lockup",
    "merit",
    "minnow",
    "miser",
    "mohawk",
    "mural",
    "music",
    "neptune",
    "newborn",
    "nightbird",
    "obtuse",
    "offload",
    "oilfield",
    "optic",
    "orca",
    "payday",
    "peachy",
    "pheasant",
    "physique",
    "playhouse",
    "pluto",
    "preclude",
    "prefer",
    "preshrunk",
    "printer",
    "profile",
    "prowler",
    "pupil",
    "puppy",
    "python",
    "quadrant",
    "quiver",
    "quota",
    "ragtime",
    "ratchet",
    "rebirth",
    "reform",
    "regain",
    "reindeer",
    "rematch",
    "repay",
    "retouch",
    "revenge",
    "reward",
    "rhythm",
    "ringbolt",
    "robust",
    "rocker",
    "ruffled",
    "sawdust",
    "scallion",
    "scenic",
    "scorecard",
    "scotland",
    "seabird",
    "select",
    "sentence",
    "shadow",
    "showgirl",
    "skullcap",
    "skydive",
    "slingshot",
    "slothful",
    "slowdown",
    "snapline",
    "snapshot",
    "snowcap",
    "snowslide",
    "solo",
    "spaniel",
    "spearhead",
    "spellbind",
    "spheroid",
    "spigot",
    "spindle",
    "spoilage",
    "spyglass",
    "stagehand",
    "stagnate",
    "stairway",
    "standard",
    "stapler",
    "steamship",
    "stepchild",
    "sterling",
    "stockman",
    "stopwatch",
    "stormy",
    "sugar",
    "surmount",
    "suspense",
    "swelter",
    "tactics",
    "talon",
    "tapeworm",
    "tempest",
    "tiger",
    "tissue",
    "tonic",
    "tracker",
    "transit",
    "trauma",
    "treadmill",
    "trojan",
    "trouble",
    "tumor",
    "tunnel",
    "tycoon",
    "umpire",
    "uncut",
    "unearth",
    "unwind",
    "uproot",
    "upset",
    "upshot",
    "vapor",
    "village",
    "virus",
    "vulcan",
    "waffle",
    "wallet",
    "watchword",
    "wayside",
    "willow",
    "woodlark",
    "zulu",
];

/// PGP Word List for odd byte positions (three-syllable words)
///
/// Maps byte values 0x00-0xFF to phonetically distinct three-syllable words.
pub const ODD_WORDS: [&str; 256] = [
    "adroitness",
    "adviser",
    "aggregate",
    "alkali",
    "almighty",
    "amulet",
    "amusement",
    "antenna",
    "applicant",
    "apollo",
    "armistice",
    "article",
    "asteroid",
    "atlantic",
    "atmosphere",
    "autopsy",
    "babylon",
    "backwater",
    "barbecue",
    "belowground",
    "bifocals",
    "bodyguard",
    "borderline",
    "bottomless",
    "bradbury",
    "brazilian",
    "breakaway",
    "burlington",
    "businessman",
    "butterfat",
    "camelot",
    "candidate",
    "cannonball",
    "capricorn",
    "caravan",
    "caretaker",
    "celebrate",
    "cellulose",
    "certify",
    "chambermaid",
    "cherokee",
    "chicago",
    "clergyman",
    "coherence",
    "combustion",
    "commando",
    "company",
    "component",
    "concurrent",
    "confidence",
    "conformist",
    "congregate",
    "consensus",
    "consulting",
    "corporate",
    "corrosion",
    "councilman",
    "crossover",
    "cumbersome",
    "customer",
    "dakota",
    "decadence",
    "december",
    "decimal",
    "designing",
    "detector",
    "detergent",
    "determine",
    "dictator",
    "dinosaur",
    "direction",
    "disable",
    "disbelief",
    "disruptive",
    "distortion",
    "divisive",
    "document",
    "embezzle",
    "enchanting",
    "enrollment",
    "enterprise",
    "equation",
    "equipment",
    "escapade",
    "eskimo",
    "everyday",
    "examine",
    "existence",
    "exodus",
    "fascinate",
    "filament",
    "finicky",
    "forever",
    "fortitude",
    "frequency",
    "gadgetry",
    "galveston",
    "getaway",
    "glossary",
    "gossamer",
    "graduate",
    "gravity",
    "guitarist",
    "hamburger",
    "hamilton",
    "handiwork",
    "hazardous",
    "headwaters",
    "hemisphere",
    "hesitate",
    "hideaway",
    "holiness",
    "hurricane",
    "hydraulic",
    "impartial",
    "impetus",
    "inception",
    "indigo",
    "inertia",
    "infancy",
    "inferno",
    "informant",
    "insincere",
    "insurgent",
    "integrate",
    "intention",
    "inventive",
    "istanbul",
    "jamaica",
    "jupiter",
    "leprosy",
    "letterhead",
    "liberty",
    "maritime",
    "matchmaker",
    "maverick",
    "medusa",
    "megaton",
    "microscope",
    "microwave",
    "midsummer",
    "millionaire",
    "miracle",
    "misnomer",
    "molasses",
    "molecule",
    "montana",
    "monument",
    "mosquito",
    "narrative",
    "nebula",
    "newsletter",
    "norwegian",
    "october",
    "ohio",
    "onlooker",
    "opulent",
    "orlando",
    "outfielder",
    "pacific",
    "pandemic",
    "pandora",
    "paperweight",
    "paragon",
    "paragraph",
    "paramount",
    "passenger",
    "pedigree",
    "pegasus",
    "penetrate",
    "perceptive",
    "performance",
    "pharmacy",
    "phonetic",
    "photograph",
    "pioneer",
    "pocketful",
    "politeness",
    "positive",
    "potato",
    "processor",
    "prophecy",
    "provincial",
    "proximate",
    "puberty",
    "publisher",
    "pyramid",
    "quantity",
    "racketeer",
    "rebellion",
    "recipe",
    "recover",
    "repellent",
    "replica",
    "reproduce",
    "resistor",
    "responsive",
    "retraction",
    "retrieval",
    "retrospect",
    "revenue",
    "revival",
    "revolver",
    "sahara",
    "sandalwood",
    "sardonic",
    "saturday",
    "savagery",
    "scavenger",
    "sensation",
    "sociable",
    "souvenir",
    "specialist",
    "speculate",
    "stethoscope",
    "stupendous",
    "supportive",
    "surrender",
    "suspicious",
    "sympathy",
    "tambourine",
    "telephone",
    "therapist",
    "tobacco",
    "tolerance",
    "tomorrow",
    "torpedo",
    "tradition",
    "travesty",
    "trombonist",
    "truncated",
    "typewriter",
    "ultimate",
    "undaunted",
    "underfoot",
    "unicorn",
    "unify",
    "universe",
    "unravel",
    "upcoming",
    "vacancy",
    "vagabond",
    "versatile",
    "vertigo",
    "virginia",
    "visitor",
    "vocalist",
    "voyager",
    "warranty",
    "waterloo",
    "whimsical",
    "wichita",
    "wilmington",
    "wyoming",
    "yesteryear",
    "yucatan",
];

// Compile-time invariant: both word lists must cover all 256 byte values.
// Although [&str; 256] already encodes the length in the type, these assertions
// make the requirement explicit and will catch a future type change (e.g. to
// &[&str]) before it silently breaks the runtime coverage test.
const _: () = assert!(
    EVEN_WORDS.len() == 256,
    "EVEN_WORDS must have exactly 256 entries"
);
const _: () = assert!(
    ODD_WORDS.len() == 256,
    "ODD_WORDS must have exactly 256 entries"
);

/// Convert a byte slice to PGP Word List representation
///
/// Each byte is converted to a word from either the even or odd word list
/// depending on its position in the input slice (0-indexed).
///
/// # Arguments
///
/// * `bytes` - The byte slice to convert
///
/// # Returns
///
/// A string containing space-separated words representing the input bytes
///
/// # Examples
///
/// ```
/// use minisign::wordlist::bytes_to_words;
///
/// // First byte (position 0, even) -> "aardvark"
/// // Second byte (position 1, odd) -> "adviser"
/// let bytes = [0x00, 0x01];
/// let words = bytes_to_words(&bytes);
/// assert_eq!(words, "aardvark adviser");
/// ```
#[must_use]
pub fn bytes_to_words(bytes: &[u8]) -> String {
    bytes
        .iter()
        .enumerate()
        .map(|(i, &byte)| {
            if i % 2 == 0 {
                EVEN_WORDS[usize::from(byte)]
            } else {
                ODD_WORDS[usize::from(byte)]
            }
        })
        .collect::<Vec<&str>>()
        .join(" ")
}

/// Convert a `KeyNum` (8-byte key identifier) to PGP Word List representation
///
/// This is a convenience wrapper around `bytes_to_words` for `KeyNum` types,
/// producing exactly 8 words (one per byte).
///
/// # Arguments
///
/// * `keynum` - The key number to convert
///
/// # Returns
///
/// A string containing 8 space-separated words representing the key ID
///
/// # Examples
///
/// ```no_run
/// use minisign::crypto::KeyNum;
/// use minisign::wordlist::keynum_to_words;
///
/// let keynum = KeyNum::from_bytes([0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07]);
/// let words = keynum_to_words(&keynum);
/// // Produces 8 words
/// assert_eq!(words.split_whitespace().count(), 8);
/// ```
#[must_use]
pub fn keynum_to_words(keynum: &KeyNum) -> String {
    bytes_to_words(keynum.as_bytes())
}
